import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import AuthProvider from "@/services/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "The Daily Post",
  description: "Generated by create next app",
};
const user = 'modarator'
export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <AuthProvider>
      <body  className={`${inter.className} bg-slate-800 `}>
       
         <Navbar></Navbar> 
        <div className={ user?`"min-h-screen  mt-5"`:"min-h-screen max-w-[1700px] mx-auto mt-5"}>
        {children}
        </div>
       
        </body>
        </AuthProvider>
    </html>
  );
}
